### ISSUE TITLE
Ask for help for installing gmhi2 in my linux computer

### ISSUE THREAD

**Issue by zbyloveyj** [danielchang2002/GMHI2-pipeline#1]
Hello, it is nice to see the great work! I had also fellow the ghmi1 before, which was published in NC in 2020. Now I met the question that i can't intsall the gmhi2 by conda.The code is 'conda create --name gmhi2_env -c danielchang2002 python=3.7 gmhi2', and the error showed below :
Channels:
 - danielchang2002
 - ursky
 - bioconda
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - gmhi2

Current channels:

  - https://conda.anaconda.org/danielchang2002
  - https://conda.anaconda.org/ursky
  - https://conda.anaconda.org/bioconda
  - https://conda.anaconda.org/conda-forge
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
It am looking forward to you response! Thank you!

**Comment by danielchang2002** [comment]
Hello,
Please refer to the installation section of the current github readme for instructions: https://github.com/danielchang2002/GMWI2
The command you wrote is for a previous version of our tool. Let me know if you have questions, thanks!
